#!/bin/bash
#SBATCH --partition       sugon
#SBATCH -J                namd-tyy
#SBATCH --time            30:00:00
#SBATCH --nodes           1
#SBATCH --ntasks-per-node 16
#SBATCH --cpus-per-task   1
#SBATCH --error           namd1.err
#SBATCH --output          namd1.log

ulimit -s unlimited

#export LD_LIBRARY_PATH=/public/apps/anaconda/anaconda3/2023.03/lib:$LD_LIBRARY_PATH
#export PATH=/public/apps/NAMD-EPC/src_tyy:$PATH
#export HDF5_USE_FILE_LOCKING="FALSE"
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

echo "============================================================"
module list
env | grep "MKLROOT="
echo "============================================================"
echo "Job ID: $SLURM_JOB_NAME"
echo "Job name: $SLURM_JOB_NAME"
echo "Number of nodes: $SLURM_JOB_NUM_NODES"
echo "Number of processors: $SLURM_NTASKS"
echo "Task is running on the following nodes:"
echo $SLURM_JOB_NODELIST
echo "OMP_NUM_THREADS = $SLURM_CPUS_PER_TASK"
echo "============================================================"
echo

srun --mpi=pmi2 /data3/tuyy/namd-epc/task2/src/namd-epc
